### ISSUE TITLE
No such component directory

### ISSUE THREAD

**Issue by robmarkcole** [lit26/streamlit-image-label#1]
On running I get:

```
streamlit.errors.StreamlitAPIException: No such component directory: '/Users/robin/Documents/GitHub/streamlit-img-label/streamlit_img_label/frontend/build```

Is there another dependency or step required?
Thanks

**Comment by robmarkcole** [comment]
OK managed to get passed that by creating a new dir at that location and copying the contents of `frontend`/public` there, then I get:

![image](https://user-images.githubusercontent.com/11855322/152522295-2154ef68-c91d-4707-8f43-45caa6397589.png)

Note I am running with `streamlit run app.py`

**Comment by lit26** [comment]
Do you clone on github or download from pypi?

**Comment by robmarkcole** [comment]
Github, via this fork https://github.com/robmarkcole/streamlit-img-label

I also get this error if I install via `pip install -e .` in my fork venv

**Comment by lit26** [comment]
I think streamlit doesn't work in the venv. You can install the package globally using pip install.

**Comment by robmarkcole** [comment]
I don't think that's the case as I always use a venv with streamlit. My guess is a missing dependency - which would be easy to miss if installing globally

**Comment by lit26** [comment]
I think the problem is from the frontend folder. The problem is you are missing `build` folder. If you directly download the repo, the `build` folder is not there. `build` folder is different from `public` folder so copying does not work. Have you install the `streamlit-img-label` package in your virtual environment?

**Comment by robmarkcole** [comment]
Yes i have `streamlit-img-label` in the venv. There is a sequence of commands to create the `build` ?

**Comment by lit26** [comment]
I have added the `build` folder to the repo. Or you can run `npm install` to install the frontend packages and run `npm run build` to create the `build` folder.

**Comment by robmarkcole** [comment]
OK running `npm run build` resolved this issue, thanks!
